config/routes.rb
Rails.application.routes.draw do

  resources :tasks do
    member do
      put :change
    end
  end

  devise_for :users, :controllers => {:omniauth_callbacks => "callbacks"}

  root 'pages#home'

  get 'about' => "pages#about"

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user

	validates :user_id, presence: true
	validates :content, presence: true

	# where is it going to get the raw html in the browser so it can display it
	auto_html_for :content do 
		html_escape
		image
		youtube(:width => "100%", :height => 250, :autoplay => false)
		link :target => "_blank", :rel => "nofollow"
		simple_format
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  		user.uid = auth.uid
  		user.name = auth.info.name
  		user.email = auth.info.email
  		user.image = auth.info.image

  		user.password = Devise.friendly_token[0,20]
  	end
  end


  # if a user deletes his account all tasks relating to him are also deleted
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  after_filter :flash_to_headers
 
  private
 
    def flash_to_headers
      return unless request.xhr?
      msg = flash_message
      #replace german umlaute encoded in utf-8 to html escaped ones
      msg = msg.gsub("ä","&auml;").gsub("ü","&uuml;").gsub("ö","&ouml;").gsub("Ä","&Auml;").gsub("Ü","&Uuml;").gsub("Ö","&Ouml;").gsub("ß","&szlig;")
      response.headers['X-Message'] = msg
      response.headers["X-Message-Type"] = flash_type.to_s
 
      flash.discard # don't want the flash to appear when you reload page
    end
 
    def flash_message
      [:error, :warning, :notice].each do |type|
        return flash[type] unless flash[type].blank?
      end
      # if we don't return something here, the above code will return "error, warning, notice"
      return ''
    end
 
    def flash_type
      #:keep will instruct the js to not update or remove the shown message.
      #just write flash[:keep] = true (or any other value) in your controller code
      [:error, :warning, :notice, :keep].each do |type|
        return type unless flash[type].blank?
      end
      #don't return the array from above which would happen if we don't have an explicit return statement
      #returning :empty will also allow you to easily know that no flash message was transmitted
      return :empty
    end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController

	def facebook
		@user = User.from_omniauth(request.env["omniauth.auth"])
		sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	if current_user
  		redirect_to tasks_path
  	end
  end

  def about
  end
  
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_task, only: [:show, :edit, :update, :destroy, :change]

  # GET /tasks
  # GET /tasks.json
  def index
    # assosiated that current user with all the tasks he has (related to the state)
    @to_do = current_user.tasks.where(state: "to_do") 
    @doing = current_user.tasks.where(state: "doing")
    @done = current_user.tasks.where(state: "done")
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    # every time a task is made it will assosiate it with a current user
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
        format.js
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  def change
    @task.update_attributes(state: params[:state])
    # after task update is complete, setting format of resulting file
    # the html format is what we want, we redirect to the tasks path (after updated the states params)
    respond_to do |format|
      format.html {redirect_to tasks_path, notice: "Task Updated"}
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def resource_name
		:user
	end

	def resource_class
		User
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "<i class='fa fa-check'></i> Done".html_safe, root_path, class: "navbar-brand" %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        
        <% if current_user %>
        <li><%= link_to "Tasks", tasks_path %> </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <% if current_user.name %>
          <%= image_tag(current_user.image, width: '20', height: '20') %><%= current_user.name %>
          <% else %>
          <%= current_user.email %>
          <% end %>
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
             <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
       
        <% else %>

        <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<% if current_page?(root_url) %>
  <html class="landing_page">
<% else %>
  <html>
<% end %>

<head>
  <title>Done</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if !current_page?(root_url) %>
	<%= render "layouts/header" %>
<% end %>



<div class="container">
	<%= yield %>
</div>
</body>
</html>

app/views/pages/_signin.html.erb
<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: "form-signin"}) do |f| %>
		<h2 class="text-center">Log in</h2>
    <%= f.input :email, required: true, autofocus: true, label: false, placeholder: "Email", input_html: {class: "form-control"} %>
    <%= f.input :password, required: true, label: false, placeholder: "Password", input_html: {class: "form-control"}  %>

    <%= f.button :submit, "Log in", class: "btn btn-primary btn-block" %><br />

    <%- resource_class.omniauth_providers.each do |provider| %>
    	<%= link_to "<i class='fa fa-facebook-official fa-1x'></i> Sign in with #{provider.to_s.titleize}".html_safe, omniauth_authorize_path(resource_name, provider), class: "hero-facebook text-center" %><br />
		<% end -%>
		<%= link_to "Sign up", "#", class: "btn btn-primary btn-block change_form" %><br />

<% end %>

app/views/pages/_signup.html.erb
<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: "form-signin"}) do |f| %>
	<h2 class="text-center">Sign up</h2>
  <%= f.error_notification %>

    <%= f.input :email, required: true, autofocus: true, label: false, placeholder: "Email", input_html: {class: "form-control"} %>
    <%= f.input :password, required: true, label: false, placeholder: "Password", input_html: {class: "form-control"} %>
    <%= f.input :password_confirmation, required: true, label: false, placeholder: "Password Confirmation", input_html: {class: "form-control"} %>


    <%= f.button :submit, "Sign up", class: "btn btn-primary btn-block" %><br />

    <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "<i class='fa fa-facebook-official fa-1x'></i> Sign in with #{provider.to_s.titleize}".html_safe, omniauth_authorize_path(resource_name, provider), class: "hero-facebook text-center" %><br />
		<% end -%>
		<%= link_to "Log in", "#", class: "btn btn-primary btn-block change_form" %><br />

<% end %>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p> Our Vision is to improve people's productivity</p>

app/views/pages/home.html.erb
<div class="form">
	<div class="signup">
		<%= render 'signup' %>
	</div>
	<div class="signin">
		<%= render 'signin' %>
	</div>

</div>

app/views/tasks/_dialog.html.erb
<div class="modal fade"
           id="dialog" tabindex="-1" role="dialog" 
           aria-labelledby="myModalLabel"
           aria-hidden="true" 
           data-backdrop="static" 
           data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header text-center">
        <button type="button" class="close" 
                data-dismiss="modal" 
                aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>
     
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/tasks/_form.html.erb
<%= simple_form_for(@task, remote: true, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>


    <%= f.input :content, label: false, required: true, autofocus: true, input_html: {class: "form-control "}, placeholder: "Content" %>
    <%= f.button :submit, class: "btn btn-md btn-primary btn-block" %>

<% end %>

app/views/tasks/_task.html.erb
<div class="panel panel-default" id="tasks_<%=task.id%>"> 


	<div class="panel-heading">
		<%= link_to "<i class='fa fa-pencil fa-2x'></i>".html_safe, edit_task_path(task), remote: true, class: "pull-right" %>




		<%= link_to "<i class='fa fa-trash-o fa-2x'></i>".html_safe, task_path(task), remote: true, method: :delete, data: {confirm: "Are you sure?"}, class: "pull-left" %>
		<p class="text-center">created <%= time_ago_in_words(task.created_at) %> ago</p>
	</div>


	<div class=" background-grey">
		<% if task.state == "doing" %>
		<%= link_to "<i class='fa fa-arrow-left fa-2x'></i>".html_safe, change_task_path(task, state: "to_do"), method: :put, remote: true, class: "center-arrow-left" %>
		<%= link_to "<i class='fa fa-arrow-right fa-2x'></i>".html_safe, change_task_path(task, state: "done"), method: :put, remote: true, class: "center-arrow-right" %>
		<% elsif task.state == "done" %>
		<%= link_to "<i class='fa fa-arrow-left fa-2x'></i>".html_safe, change_task_path(task, state: "doing"), method: :put, remote: true, class: "center-arrow-left" %>
		<% else %>
		<%= link_to "<i class='fa fa-arrow-right fa-2x'></i>".html_safe, change_task_path(task, state: "doing"), method: :put, remote: true, class: "center-arrow-right" %>
		<% end %>

		<div class="panel-body fixed-panel text-center"><%= raw(task.content_html) %>

		</div>
	</div>





	<div class="panel-footer">

	</div>

</div>


<script>

	<% if task.state == "to_do" %>
		$("#tasks_to_do .fixed-panel p").css("border-top-color", "#f90d56");
	<% elsif task.state == "doing" %>
		$("#tasks_doing .fixed-panel p").css("border-top-color", "#ff970c");
	<% else %>
		$("#tasks_done .fixed-panel p").css("border-top-color", "#ffe801");
	<% end %>

</script>

app/views/tasks/change.js.erb
$('#tasks_<%= @task.id %>').fadeOut();
$('#tasks_<%= @task.id %>').appendTo('#tasks_<%= @task.state %>').replaceWith('<%= j render (@task) %>')
$('#tasks_<%= @task.id %>').fadeIn();

app/views/tasks/create.js.erb
$('#dialog').modal('toggle');
$('.tasks').append('<%= j render (@task) %>');

app/views/tasks/destroy.js.erb
$('#tasks_<%= @task.id %>').fadeOut();

app/views/tasks/edit.js.erb
$('#tasks_<%=@task.id%> .panel-body').replaceWith('<%= j render("form") %>');

app/views/tasks/index.html.erb
<div class="row">
  <div class="col-md-4 tasks", id="tasks_to_do">
    <h1 class="text-center">To Do</h1>

    <div class="panel panel-default"> 
      <div class="panel-heading new-task text-center">
        <%= link_to "<i class='fa fa-plus-circle fa-4x'></i>".html_safe, new_task_path, remote: true, class: "" %>
      </div>
    </div>




      <%= render @to_do %>
  </div>

  <div class="col-md-4", id="tasks_doing">
    <h1 class="text-center">Doing</h1>
    <%= render @doing %>
  </div>

  <div class="col-md-4"id="tasks_done">
    <h1 class="text-center">Done</h1>
    <%= render @done %>
  </div>
</div><!-- end of row class -->

<br>


<%= render 'dialog' %>

app/views/tasks/new.js.erb
$('.modal-title').html('New Item');
$('.modal-body').html('<%= j render("form") %>');
$('#dialog').modal("show");

app/views/tasks/update.js.erb
$('#tasks_<%=@task.id%>').replaceWith('<%= j render (@task) %>');